version: '3.8'

services:
  db:
    image: postgres:15
    container_name: cdgxpress_db
    environment:
      POSTGRES_USER: cdgxpress_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cdgxpress
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cdgxpress_user -d cdgxpress"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  backend:
    build: ./backend
    container_name: cdgxpress_backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: cdgxpress_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cdgxpress
      POSTGRES_PORT: 5432
      HOST: 0.0.0.0
      PORT: 3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s



volumes:
  db_data:
